# This is a basic workflow to help you get started with Actions

name: "Deploy on Comment"

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'lcc-200')
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          
      - name: Get PR comment
        uses: actions-ecosystem/action-regex-match@v2
        id: get-pr-comment
        with:
          text: ${{ github.event.comment.body }}
          regex: '(?<=#)\d+'

      - name: Echo extracted title
        run: |
          echo "${{ steps.get-pr-comment.outputs.group1 }}"

      - name: Commit report
        run: |
          git commit --allow-empty -m  "Fixed AD#${{ steps.get-pr-comment.outputs.group1 }}"
          git push
