# This is a basic workflow to help you get started with Actions
#sa
name: "Deploy on Comment"

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'lcc-200')
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          

      - name: Set env var
        run: |
          result=$(echo "${{ github.event.comment.body }}" | grep -oP '(?<=#)\d+')
          echo "TEST=${result}" >> $GITHUB_ENV

          

      - name: Echo extracted title
        run: |
          echo "${{TEST}}"

#      - name: Commit report
#        run: |
#          git config --global user.name "p3dr0rv"
#          git config --global user.email "pedroro@microsoft.com"
#          git commit --allow-empty -m  "Fixed AD#${{ steps.get-pr-comment.outputs.group1 }}"
#          git push
